### ISSUE TITLE
Fix dumb terminal example

### ISSUE THREAD

**Issue by Nerdmaster** [Nerdmaster/terminal#3]
Here's a thought - maybe these should all be TESTED in various environments... via something automated!

Nah, that's too crazy.

**Comment by tectiv3** [comment]
I run dumb terminal example on win 10, it works.
```
PS Z:\src\github.com\Nerdmaster\terminal> go run .\example\dumb.go
I'm thinking of a number from 1-10.  Try to guess it!
(Type 'QUIT' at any time to exit)

Guess a number: 22
Please enter a number in the range of 1 to 10, inclusive
Guess a number: 1
1 is WRONG!  Try again!
Guess a number: 2
```

**Comment by Nerdmaster** [comment]
I honestly don't know how I have survived this long.

I just tested and it works fine.  I must have done something stupid like `go run dumb_termina.go` (the package, not the example).  And ... not noticed the very obvious error message...?

Thanks for the sanity check!
