### ISSUE TITLE
terminal.NewPrompt() not working as expected

### ISSUE THREAD

**Issue by victpork** [Nerdmaster/terminal#4]
When running the example code example/prompt.go, the output echo seems limited to single character. All subsequent key sequence overwrite the same position forever. Same thing happens on ssh channel (ssh.Channel as io.Reader/Writer) and STDIO (os.Stdin/Stdout). However the keylogger callback function work as expected.

**Comment by Nerdmaster** [comment]
Stupid error on my part; this should be fixed in v0.12.1
